---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/visiobno/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R php $DEPLOYPATH
    - /bin/cp -R webfonts $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
